MRuby::Gem::Specification.new('mruby-gpu-narray') do |spec|
  spec.license = 'MIT'
  spec.authors = 'Yuji Teshima'
  spec.summary = 'GPU N-dimensional array (Numo-like) for mruby via Vulkan Compute'

  # Only dependency is the Vulkan loader. No ncnn / SDL2 / glslang / OpenMP.
  spec.linker.libraries << 'vulkan'

  # Embed the absolute shader directory into a generated header so that
  # GPU.init is optional (the first GPU op can lazily initialize).
  #
  # We write a header instead of using spec.cc.defines to avoid the shell
  # quote-escaping fragility of passing a string literal through -D.
  gem_dir    = File.dirname(File.expand_path(__FILE__))
  shader_dir = File.join(gem_dir, 'shader')
  File.write(File.join(gem_dir, 'src', 'shader_dir.h'),
             "/* auto-generated by mrbgem.rake -- do not edit, do not commit */\n" \
             "#define GPU_NARRAY_SHADER_DIR \"#{shader_dir}\"\n")
end
